version: "3.8"

services:
  react-native-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081" # Metro Bundler port
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start
